"""Curated fallback questions, used when Groq is unavailable or no API key is configured.

Three questions per seeded topic. Each is written as (question, correct answer, three wrong
answers, explanation); the correct answer is listed first only for readability. Options are
shuffled every time a quiz is served, so the stored position reveals nothing.
"""

from typing import Any


def _q(question: str, answer: str, wrong: tuple[str, str, str], explanation: str) -> dict[str, Any]:
    return {"question": question, "options": [answer, *wrong], "correct": 0, "explanation": explanation}


FALLBACK_QUESTIONS: dict[str, list[dict[str, Any]]] = {
    "html_basics": [
        _q("Which element creates a hyperlink to another page?", "<a>", ("<link>", "<href>", "<url>"),
           "The anchor element <a> with an href attribute creates a hyperlink. <link> connects external "
           "resources such as stylesheets."),
        _q("Which attribute provides alternative text for an image?", "alt", ("title", "src", "desc"),
           "alt describes the image for screen readers and is shown if the image fails to load."),
        _q("Which tag is the most important (top-level) heading?", "<h1>", ("<h6>", "<head>", "<header>"),
           "Headings run from <h1> (most important) to <h6>. <head> holds page metadata and <header> is a "
           "sectioning element."),
    ],
    "semantic_html": [
        _q("Which element should wrap a site's main navigation links?", "<nav>",
           ("<menu>", '<div class="nav">', "<aside>"),
           "<nav> marks a block of major navigation links, which assistive technology can jump straight to."),
        _q("What is the purpose of the <main> element?",
           "To hold the dominant content that is unique to the page",
           ("To load the page's main JavaScript file", "To mark the first section of the page",
            "To wrap everything inside <body>"),
           "<main> contains the content unique to that page; there should be only one visible <main> per page."),
        _q("Why prefer semantic elements over generic <div>s where they fit?",
           "They convey meaning to browsers, search engines and assistive technology",
           ("They render faster than <div>s", "CSS only works on semantic elements",
            "They add default animations"),
           "Semantic elements describe what content is, which improves accessibility and SEO; they don't "
           "change performance or styling ability."),
    ],
    "forms_accessibility": [
        _q("What is the most reliable way to give a text input an accessible label?",
           "A <label> whose for attribute matches the input's id",
           ("A placeholder attribute", "A title attribute", "Plain text placed just before the input"),
           "A linked <label> is announced by screen readers and enlarges the click target. Placeholders "
           "disappear while typing and are not a substitute for labels."),
        _q("Which input type shows an email keyboard on phones and validates the format?", 'type="email"',
           ('type="text"', 'type="mail"', 'type="string"'),
           'type="email" gives built-in format validation and a suitable on-screen keyboard.'),
        _q("What does the required attribute on an input do?",
           "Stops the form submitting while the field is empty",
           ("Makes the field's text bold", "Sends that field to the server first", "Encrypts the field's value"),
           "required enables built-in validation: the browser blocks submission and shows a message until "
           "the field has a value."),
    ],
    "css_basics": [
        _q("Which selector has the highest specificity?", "#header", (".header", "header", "*"),
           "ID selectors outrank class selectors, which outrank type selectors; the universal selector adds "
           "no specificity."),
        _q("With box-sizing: content-box (the default), what does width set?", "The content area only",
           ("Content plus padding", "Content, padding and border", "Content, padding, border and margin"),
           "With content-box, padding and border are added on top of width. box-sizing: border-box includes "
           "them in the width instead."),
        _q("Which CSS property changes the colour of text?", "color", ("font-color", "text-color", "foreground"),
           "The color property sets the text (foreground) colour; the other names are not CSS properties."),
    ],
    "flexbox": [
        _q("Which declaration turns an element into a flex container?", "display: flex",
           ("flex: 1", "position: flex", "flex-direction: row"),
           "display: flex makes the element a flex container and its children flex items."),
        _q("With flex-direction: row, which property positions items along the horizontal axis?",
           "justify-content", ("align-items", "align-content", "text-align"),
           "justify-content works on the main axis (horizontal for row); align-items works on the cross axis."),
        _q("What does flex-wrap: wrap allow?", "Items move onto a new line when they don't fit",
           ("Text wraps inside each item", "Items shrink to zero width", "The container scrolls horizontally"),
           "By default flex items stay on one line; wrap lets them flow onto additional lines."),
    ],
    "css_grid": [
        _q("What does grid-template-columns: 1fr 2fr create?",
           "Two columns, the second twice as wide as the first",
           ("Two equal columns", "One column and two rows", "Three equal columns"),
           "fr shares out free space; 1fr 2fr splits it 1:2 between two columns."),
        _q("Which property sets the spacing between grid rows and columns?", "gap",
           ("margin", "padding", "grid-spacing"),
           "gap (or row-gap/column-gap) sets gutters between tracks without adding outer margins."),
        _q("When is CSS Grid usually a better fit than Flexbox?",
           "When laying out content in rows and columns at the same time",
           ("When centring a single icon in a button", "When spacing items along one row",
            "When animating elements"),
           "Grid is two-dimensional (rows and columns); Flexbox is one-dimensional."),
    ],
    "responsive_design": [
        _q("What does @media (max-width: 600px) { ... } do?",
           "Applies the rules only when the viewport is 600px wide or narrower",
           ("Limits the page width to 600px", "Applies the rules only above 600px", "Scales images to 600px"),
           "A max-width media query matches viewports up to and including that width."),
        _q('Why include <meta name="viewport" content="width=device-width, initial-scale=1">?',
           "So mobile browsers lay out the page at the device's width instead of a zoomed-out desktop width",
           ("To enable media queries in desktop browsers", "To make images responsive automatically",
            "To stop users from zooming"),
           "Without it, mobile browsers render at a wide virtual width and shrink the page, so responsive "
           "styles don't apply as intended."),
        _q("What does a mobile-first approach mean?",
           "Write base styles for small screens, then add min-width media queries for larger ones",
           ("Build a separate site for mobile", "Hide content on small screens", "Use only pixel units"),
           "Mobile-first starts from the smallest layout and progressively enhances for wider screens."),
    ],
    "javascript_fundamentals": [
        _q("Which keyword declares a variable that cannot be reassigned?", "const", ("let", "var", "static"),
           "const prevents reassigning the binding (an object it holds can still be changed)."),
        _q('What does 2 + "2" evaluate to in JavaScript?', '"22"', ("4", "NaN", "A TypeError"),
           "When either operand of + is a string, JavaScript converts the other to a string and concatenates."),
        _q("What is the difference between == and ===?",
           "=== compares without type conversion; == converts types first",
           ("There is no difference", "== is for numbers and === is for strings", "=== assigns a value"),
           "Strict equality (===) checks value and type, avoiding surprises like 0 == '' being true."),
    ],
    "functions_scope": [
        _q("What is a closure?", "A function that remembers variables from the scope where it was created",
           ("A function that closes the browser tab", "A function with no return value",
            "A way to exit a loop early"),
           "Inner functions keep access to their outer scope's variables even after the outer function returns."),
        _q("Where can a variable declared with let inside an if block be used?", "Only inside that block",
           ("Anywhere in the enclosing function", "Anywhere in the program", "Only in the next block"),
           "let and const are block-scoped; var is function-scoped."),
        _q("What does a function return if it has no return statement?", "undefined", ("null", "0", "An empty string"),
           "Functions without an explicit return value return undefined."),
    ],
    "arrays_objects": [
        _q("What does [1, 2, 3].map(x => x * 2) return?", "[2, 4, 6]", ("[1, 2, 3]", "12", "[2]"),
           "map returns a new array with the callback applied to every element; the original is unchanged."),
        _q("Which array method returns every element that passes a test?", "filter", ("map", "find", "forEach"),
           "filter returns a new array of all matches; find returns only the first match."),
        _q("What does const { name } = user; do?", "Creates a variable name holding user.name",
           ("Renames user to name", "Deletes user.name", "Throws a SyntaxError"),
           "Object destructuring copies the matching property into a new variable."),
    ],
    "dom_manipulation": [
        _q("Which method returns the first element matching a CSS selector?", "document.querySelector()",
           ("document.querySelectorAll()", "document.getElementsByClassName()", "document.getElementById()"),
           "querySelector takes any CSS selector and returns the first match; querySelectorAll returns all of them."),
        _q("Why is textContent safer than innerHTML for inserting user-provided text?",
           "textContent treats the value as plain text, so it can't inject HTML or scripts",
           ("textContent is always faster", "innerHTML has been removed from browsers",
            "textContent keeps CSS styles"),
           "innerHTML parses markup, which can enable cross-site scripting (XSS) with untrusted input."),
        _q("After document.createElement('li'), how does the new element appear on the page?",
           "It must be inserted into the document, e.g. list.appendChild(li)",
           ("It appears automatically", "By calling li.render()", "By setting li.visible = true"),
           "createElement only creates a detached node; it shows up once added to the DOM tree."),
    ],
    "browser_events": [
        _q("Which call attaches a click handler to a button element?",
           "button.addEventListener('click', handler)",
           ("button.onClick(handler)", "button.listen('click', handler)", "button.attach('click', handler)"),
           "addEventListener is the standard way to register event handlers and allows several per event."),
        _q("What does event.preventDefault() do in a form's submit handler?",
           "Stops the browser's default action, such as reloading the page on submit",
           ("Stops other listeners from running", "Removes the event listener", "Stops the event from bubbling"),
           "preventDefault cancels the default behaviour; stopPropagation is what stops bubbling."),
        _q("What is event delegation?",
           "Handling events for many children with one listener on a parent, using event bubbling",
           ("Sending events to a server", "Delaying an event until later", "Creating custom event types"),
           "Because events bubble up, one parent listener can handle clicks on current and future children."),
    ],
    "async_javascript": [
        _q("What does an async function always return?", "A Promise",
           ("undefined", "Its value immediately", "A callback function"),
           "async functions wrap their result in a Promise, even when returning a plain value."),
        _q("In what order is this logged? console.log('A'); setTimeout(() => console.log('B'), 0); console.log('C');",
           "A, C, B", ("A, B, C", "B, A, C", "C, A, B"),
           "The setTimeout callback is queued and runs only after the current script finishes, even with a 0ms delay."),
        _q("How do you handle a rejected promise when using await?", "Wrap the await in try/catch",
           ("Use an if/else around it", "It cannot be handled", "Only with a finally block"),
           "await throws the rejection reason, so try/catch handles it like a normal error."),
    ],
    "fetch_http_apis": [
        _q("Does fetch() reject its promise when the server responds with HTTP 404?",
           "No - it resolves, so you must check response.ok or response.status",
           ("Yes, any non-200 response rejects", "It returns null", "It retries automatically"),
           "fetch only rejects on network failure; HTTP error statuses still resolve."),
        _q("Which HTTP method is conventionally used to create a new resource?", "POST", ("GET", "DELETE", "HEAD"),
           "POST submits data to create a resource; GET only reads."),
        _q("How do you read a JSON response body with fetch?", "await response.json()",
           ("response.body", "JSON.parse(response)", "response.data"),
           "response.json() reads the body stream and parses it, returning a promise."),
    ],
    "es_modules": [
        _q("How many default exports can one module have?", "At most one",
           ("As many as needed", "Exactly two", "None - only named exports are allowed"),
           "A module may have one default export and any number of named exports."),
        _q("How do you import the named export add from './math.js'?", "import { add } from './math.js'",
           ("import add from './math.js'", "require('add')", "import * add from './math.js'"),
           "Named exports are imported with braces; without braces you get the default export."),
        _q("Which <script> attribute loads a file as an ES module in the browser?", 'type="module"',
           ("defer", "async", 'lang="esm"'),
           'Scripts with type="module" can use import/export and are deferred by default.'),
    ],
    "git_basics": [
        _q("What does git commit do?", "Records the staged changes as a new snapshot in the local repository",
           ("Uploads changes to GitHub", "Stages every modified file", "Creates a new branch"),
           "A commit saves staged changes locally; git push is what sends commits to a remote."),
        _q("Which command stages changes for the next commit?", "git add",
           ("git push", "git save", "git stage-commit"),
           "git add moves changes into the staging area so the next commit includes them."),
        _q("What does git pull do?", "Fetches changes from a remote and merges them into the current branch",
           ("Pushes local commits to the remote", "Discards local changes", "Opens a pull request"),
           "git pull is git fetch followed by a merge (or rebase) of the remote branch."),
    ],
    "nodejs_basics": [
        _q("What is Node.js?", "A runtime that runs JavaScript outside the browser",
           ("A frontend framework", "A database", "A browser extension"),
           "Node.js runs JavaScript on servers and computers using the V8 engine."),
        _q("Where does a Node.js program read environment variables from?", "process.env",
           ("window.env", "global.config", "require.env"),
           "process.env is an object holding the environment variables of the running process."),
        _q("Why do Node.js servers rely on non-blocking (async) I/O?",
           "So one thread can keep serving other requests while waiting for disk or network",
           ("Synchronous I/O is not supported in Node.js", "It uses less memory per file", "It makes code shorter"),
           "Node.js uses an event loop; blocking calls would stall every request on that thread."),
    ],
    "npm_packages": [
        _q("What does npm install do when run without arguments in a project?",
           "Installs every dependency listed in package.json",
           ("Installs npm itself", "Publishes the package", "Updates Node.js"),
           "npm install reads package.json (and package-lock.json) and installs the listed dependencies."),
        _q("Which versions does the range ^1.4.2 allow?", "Any 1.x.x version at or above 1.4.2",
           ("Only 1.4.2", "Only 1.4.x versions", "Any version at all"),
           "The caret allows minor and patch updates but not a new major version."),
        _q("Where do you define a command that runs with npm run build?", 'The "scripts" section of package.json',
           ("The node_modules folder", "The .npmrc file", "package-lock.json"),
           'npm run <name> executes the matching entry in package.json "scripts".'),
    ],
    "express_basics": [
        _q("How do you handle GET requests to /users in Express?", "app.get('/users', (req, res) => { ... })",
           ("app.route('GET /users')", "app.listen('/users')", "express.get('/users')"),
           "app.get registers a route handler for GET requests to that path."),
        _q("What is middleware in Express?",
           "A function that runs between receiving a request and sending the response, with access to req, res and next",
           ("The database layer", "A template engine", "A test runner"),
           "Middleware can read or modify req/res, end the request, or call next() to pass control on."),
        _q("How do you send a JSON response in Express?", "res.json(data)",
           ("res.send.json(data)", "req.json(data)", "res.write(JSON)"),
           "res.json serialises the data and sets the Content-Type header to application/json."),
    ],
    "rest_api_design": [
        _q("Which status code best fits successfully creating a resource?", "201 Created",
           ("200 OK", "204 No Content", "302 Found"),
           "201 signals that a new resource was created, often with its location or body in the response."),
        _q("Which request best follows REST conventions to fetch the user with id 42?", "GET /users/42",
           ("GET /getUser?id=42", "POST /users/get/42", "GET /user-42-fetch"),
           "REST URLs name resources (nouns) and let the HTTP method express the action."),
        _q("Which HTTP method should replace a resource entirely?", "PUT", ("POST", "PATCH", "CONNECT"),
           "PUT replaces the whole resource and is idempotent; PATCH applies a partial update."),
    ],
    "authentication_basics": [
        _q("How should user passwords be stored?",
           "As salted hashes from a slow algorithm such as bcrypt or Argon2",
           ("As plain text in a secured database", "Base64-encoded", "Encrypted with a key stored alongside them"),
           "Slow salted hashes make stolen password databases very expensive to crack; encoding is reversible."),
        _q("What is the difference between authentication and authorization?",
           "Authentication verifies who you are; authorization decides what you may do",
           ("They mean the same thing", "Authentication decides what you may do; authorization verifies identity",
            "Authorization always happens before authentication"),
           "You first prove identity (authentication), then permissions are checked (authorization)."),
        _q("Why shouldn't secrets be placed in a JWT's payload?",
           "The payload is only base64url-encoded, so anyone holding the token can read it",
           ("It makes the token expire immediately", "JWTs cannot contain strings", "It invalidates the signature"),
           "A JWT signature prevents tampering but does not hide the payload."),
    ],
    "sql_basics": [
        _q("Which clause filters rows before they are grouped?", "WHERE", ("HAVING", "ORDER BY", "GROUP BY"),
           "WHERE filters individual rows; HAVING filters groups after GROUP BY."),
        _q("What does an INNER JOIN return?", "Only rows with matching values in both tables",
           ("Every row from both tables", "Every row from the left table", "Only rows without a match"),
           "INNER JOIN keeps rows where the join condition matches; LEFT JOIN also keeps unmatched left rows."),
        _q("Which statement removes specific rows that match a condition?", "DELETE ... WHERE ...",
           ("DROP TABLE ...", "ALTER TABLE ...", "UPDATE ... SET ..."),
           "DELETE with WHERE removes matching rows; DROP TABLE removes the whole table."),
    ],
    "postgresql_basics": [
        _q("What does a PRIMARY KEY constraint guarantee?", "Values are unique and never null",
           ("Rows are stored in sorted order", "Values are encrypted", "The column references another table"),
           "A primary key uniquely identifies each row, so it must be unique and NOT NULL."),
        _q("Why add an index to a column?", "To speed up lookups and filtering on that column",
           ("To make its values unique in every case", "To compress the table", "To back up the table"),
           "Indexes let the database find rows without scanning the whole table, at some cost to writes."),
        _q("Why should application code use parameterized queries instead of building SQL strings?",
           "They prevent SQL injection by sending values separately from the SQL text",
           ("They are shorter to type", "PostgreSQL rejects other queries", "They encrypt the data"),
           "With parameters, user input is always treated as data, never as SQL code."),
    ],
    "react_fundamentals": [
        _q("What is JSX?", "A syntax extension that lets you write HTML-like markup inside JavaScript",
           ("A CSS preprocessor", "A database query language", "A testing library"),
           "JSX compiles to JavaScript calls that create React elements."),
        _q("Why does React need a key prop on items rendered from a list?",
           "To identify each item so React can update the list correctly and efficiently",
           ("To style each item", "HTML requires it", "To sort the list"),
           "Stable keys let React match items between renders instead of re-creating or mixing them up."),
        _q("What does a React function component return?", "JSX (or null) describing what to render",
           ("A CSS file", "A URL to load", "Nothing - it renders itself"),
           "Components return a description of the UI; React updates the DOM to match it."),
    ],
    "props_state": [
        _q("What is the key difference between props and state?",
           "Props are passed in by the parent and read-only; state is owned and updated by the component",
           ("State is passed in by the parent; props are owned by the component", "They are the same thing",
            "State is only used for styling"),
           "Data flows down through props; a component changes only its own state."),
        _q("How should you update a value created with const [count, setCount] = useState(0)?",
           "Call the setter, e.g. setCount(count + 1)",
           ("Assign count = count + 1", "Change this.state.count", "Call render() manually"),
           "Calling the setter schedules a re-render with the new value; direct assignment is ignored."),
        _q("Two sibling components need the same data. What is the usual React approach?",
           "Lift the state up to their closest common parent and pass it down as props",
           ("Keep a separate copy of the state in each", "Use global variables", "Read each other's DOM"),
           "Lifting state up gives both siblings a single source of truth."),
    ],
    "react_hooks": [
        _q("When does useEffect(fn, []) run its effect?", "Once after the component first renders (on mount)",
           ("After every render", "Never", "Before the first render"),
           "An empty dependency array means no dependencies change, so the effect runs after the initial render "
           "(React's development StrictMode deliberately runs it twice to catch bugs)."),
        _q("Which hook keeps a mutable value across renders without causing a re-render?", "useRef",
           ("useState", "useMemo", "useEffect"),
           "Changing ref.current does not trigger a render, unlike updating state."),
        _q("Which of these is a rule of hooks?",
           "Call hooks only at the top level of a component or custom hook, not inside loops or conditions",
           ("Hooks must be async functions", "A component may use only one hook", "Hooks only work in class components"),
           "React relies on hooks being called in the same order on every render."),
    ],
    "react_router": [
        _q('Why use <Link to="/about"> instead of <a href="/about"> inside a React Router app?',
           "It changes the route on the client without a full page reload",
           ("It applies default styles", "Search engines require it", "It opens the page in a new tab"),
           "Link updates the URL through the History API so the app stays loaded and keeps its state."),
        _q("For the route path /quiz/:topicId, how does the component read topicId?", "useParams()",
           ("useLocation().topicId", "window.topicId", "It is always passed as props.topicId"),
           "useParams returns the dynamic segments of the matched route."),
        _q("Which hook navigates in code, for example after a form is submitted?", "useNavigate",
           ("useHistoryPush", "useRoute", "useRedirect"),
           "useNavigate returns a function that changes the current route programmatically."),
    ],
    "react_api_integration": [
        _q("Without a data-fetching library, where does a function component usually start fetching data?",
           "Inside a useEffect", ("Directly in the render body", "Inside the JSX", "In a CSS file"),
           "Effects run after render, which is the right place for side effects such as network requests."),
        _q("Why track loading and error states when fetching data?",
           "So the UI can show a spinner, an error message or the data instead of breaking",
           ("fetch requires it", "It caches the data", "It makes requests faster"),
           "Each state needs its own UI; without them users see blank or broken screens."),
        _q("Why ignore or cancel a request when the component unmounts or its inputs change?",
           "To avoid race conditions and setting state from an outdated response",
           ("To reduce CSS size", "fetch fails otherwise", "To clear cookies"),
           "An older request can finish after a newer one; ignoring stale responses keeps the UI correct."),
    ],
    "testing_basics": [
        _q("What is a unit test?", "A test of a small piece of code, such as one function, in isolation",
           ("A test of the whole system by real users", "A load test", "A manual click-through of the app"),
           "Unit tests are small and fast; integration and end-to-end tests cover larger parts."),
        _q("What does React Testing Library encourage?",
           "Testing components the way users use them, e.g. finding elements by role or label",
           ("Testing internal component state directly", "Only snapshot testing", "Testing CSS class names"),
           "Tests that mirror user behaviour keep passing through refactors that don't change behaviour."),
        _q("Why mock a network call in a unit test?",
           "To make the test fast and deterministic, independent of a real server",
           ("To test the network itself", "Test runners require mocks", "To hide bugs"),
           "Real network calls make tests slow and flaky; mocks give controlled responses."),
    ],
    "deployment_basics": [
        _q("Why keep secrets such as API keys in environment variables rather than in source code?",
           "So they are never committed to the repository and can differ per environment",
           ("They load faster", "JavaScript requires it", "It makes them public"),
           "Committed secrets leak through version history; environment variables keep them out of the code."),
        _q("What does npm run build usually produce for a React + Vite app?",
           "Optimised static files (HTML, JS, CSS) ready to be served",
           ("A database", "A Docker container", "A development server"),
           "The build step bundles and minifies the app into static assets for hosting."),
        _q("Why must the backend's CORS settings include the deployed frontend's origin?",
           "Browsers block cross-origin API requests that the server does not allow",
           ("To improve SEO", "To apply styles", "DNS requires it"),
           "CORS is enforced by the browser; the API must explicitly allow the frontend's origin."),
    ],
}
