from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, Field, StrictInt, StringConstraints, field_validator, model_validator

from schemas.topics import RecommendedTopic, ResourceOut, StatusValue

QUESTIONS_PER_QUIZ = 3
OPTIONS_PER_QUESTION = 4

NonEmpty = Annotated[str, StringConstraints(strip_whitespace=True, min_length=1, max_length=1000)]


def _normalise(text: str) -> str:
    return " ".join(text.lower().split())


# --- Internal: quiz content with answers (LLM output, fallback bank, quiz_sessions) ---

class QuizQuestion(BaseModel):
    """One question including its answer key. Never sent to the browser before submission."""

    question: NonEmpty
    options: list[NonEmpty] = Field(min_length=OPTIONS_PER_QUESTION, max_length=OPTIONS_PER_QUESTION)
    # StrictInt: reject "1", 1.0 and True - an LLM returning those is a malformed answer key.
    correct: StrictInt = Field(ge=0, le=OPTIONS_PER_QUESTION - 1)
    explanation: NonEmpty

    @field_validator("options")
    @classmethod
    def options_are_distinct(cls, options: list[str]) -> list[str]:
        if len({_normalise(o) for o in options}) != len(options):
            raise ValueError("options must be distinct")
        return options


class QuizContent(BaseModel):
    questions: list[QuizQuestion] = Field(min_length=QUESTIONS_PER_QUIZ, max_length=QUESTIONS_PER_QUIZ)

    @model_validator(mode="after")
    def questions_are_distinct(self) -> "QuizContent":
        if len({_normalise(q.question) for q in self.questions}) != len(self.questions):
            raise ValueError("questions must be distinct")
        return self


# --- API: what the browser receives ------------------------------------------------

class QuizQuestionOut(BaseModel):
    id: int
    question: str
    options: list[str]


class QuizTopicOut(BaseModel):
    id: str
    name: str


class GeneratedQuizResponse(BaseModel):
    quiz_id: UUID
    topic: QuizTopicOut
    questions: list[QuizQuestionOut]
    expires_in_seconds: int
    source: Literal["ai", "fallback"] = Field(
        description="'ai' when generated by the LLM, 'fallback' when served from the curated question bank"
    )


# --- Submission ---------------------------------------------------------------------

AnswerIndex = Annotated[StrictInt, Field(ge=0, le=OPTIONS_PER_QUESTION - 1)]


class QuizSubmitRequest(BaseModel):
    quiz_id: UUID
    answers: list[AnswerIndex] = Field(
        min_length=QUESTIONS_PER_QUIZ,
        max_length=QUESTIONS_PER_QUIZ,
        description="Selected option index (0-3) for each question, in question order",
        examples=[[0, 2, 1]],
    )


class AnswerFeedback(BaseModel):
    question: str
    options: list[str]
    selected: int
    correct: int
    is_correct: bool
    explanation: str


class QuizSubmitResponse(BaseModel):
    topic_id: str
    score: int
    total: int
    passed: bool
    p_know_before: float
    p_know_after: float
    mastered: bool
    status: StatusValue
    needs_attention: bool
    feedback: list[AnswerFeedback]
    recommended_resources: list[ResourceOut] = Field(
        description="Learning resources for this topic, included when the quiz was failed or the topic needs attention"
    )
    newly_unlocked: list[str] = Field(description="Topic ids this submission unlocked")
    next_topics: list[RecommendedTopic] = Field(description="Next topics to learn (at most 3)")
